### ISSUE TITLE
Android App compilation issue when Sample app is written in java

### ISSUE THREAD

**Issue by sohanlal1234** [KasperskyLab/Kaspresso#113]
Hi ,
I my sample android app in java and wrote Kaspresso sample test in koltin .
I am facing unknown compilation issue .
But same test app works fine when sample android app is written in koltin .

So My query is direct . 
**Do Kaspresso support Java ?**
1. Can we use kaspresso for Instrumentation testing for an android app written in Java ?
2. Can we write kaspresso test in Java ?

**Comment by eakurnikov** [comment]
Hello! 
It doesn't matter which language you use in the application under test - java, kotlin, or both.

So the answers are as follows:
1) Yes, of course.
2) Hmm, no, I guess, or it will be too difficult since kotlin dsl won't work, so such an experience can be terrible.

What compilation problem did you encounter?

**Comment by sohanlal1234** [comment]
Hi Eakunikov,
Thanks for reply .Hope you are doing well during .
I will update you post May 2nd Week , as I am unable to access my code from Home .

**Comment by matzuk** [comment]
@sohanlal1234 Hi! Do you have any updates?

**Comment by matzuk** [comment]
Looks outdated
