### ISSUE TITLE
Jetpack compose support

### ISSUE THREAD

**Issue by diklimchuk** [KasperskyLab/Kaspresso#249]
Given that jetpack compose is most likely to be out of beta any time soon and a lot of projects will start using it, is there any plan to support it?
Now it offers a test rule https://developer.android.com/jetpack/compose/testing. But working with views is a bit different, for example in compose Views don't have an id.

**Comment by sergio-sastre** [comment]
@diklimchuk 
Google intends to make writing jetpack compose tests compatible with Espresso. That would be the best case, since no adjustments would be necessary on Kaspresso side.
The question was replied [here](https://github.com/android/compose-samples/commit/a6907c5dc236e9c18f062c44453b1c15359962cf), and I added a comment to confirm it.
However, even in the best case, I would not expect Google to provide such functionality any time soon.
I am also curious about what incompatibility issues would arise if they manage to get it working.

**Comment by diklimchuk** [comment]
Thank you. I guess the only question left is whether kaspresso could support compose testing without espresso compatibility

**Comment by sergio-sastre** [comment]
Your question is very valid since it seems that they are not gonna make them compatible with Espresso as I thought (similar to Robolectric), but just allow to use Espresso code together with ComposeTestRule (see comment [here](https://github.com/android/compose-samples/commit/a6907c5dc236e9c18f062c44453b1c15359962cf)).
I think this would require to add the corresponding Screen and interceptors (e.g autoscroll, etc.) for Jetpack Compose. Seems like a bunch of work, but someone from the Kaspresso team can likely tell you more about that.

**Comment by matzuk** [comment]
@RuslanMingaliev @Vacxe join the conversation =)

**Comment by sergio-sastre** [comment]
I would gladly take a look at this, at least to estimate how much effort it would be.
Not sure how much time I'll get for this in the following weeks though, but hope I can make enough progress within the next 2-3 weeks ;)

**Comment by Vacxe** [comment]
@diklimchuk @sergio-sastre we have a plans add it to Kakao support about next couple month.

**Comment by sergio-sastre** [comment]
This together with #242 can become very interesting since [Jetpack compose will also support Robolectric](https://github.com/android/compose-samples/pull/556)
