### ISSUE TITLE
Target 30 support

### ISSUE THREAD

**Issue by AzamatCherchesov** [KasperskyLab/Kaspresso#404]
Correct work with storage (migrate from Manage all external storage permission to Scoped storage)

**Comment by Nikitae57** [comment]
Need to be careful with this. Whole kaspresso is built on using traditional file API. Another thing to consider is screen recording on android 10+. Current implementation uses "abd shell screenrecord path/to/save/video/on/device" (I'll call it just screen recorder onwards). 
- screen recorder could write video to /sdcard/ but we can't create any subfolders from kaspresso without MANAGE_EXTERNAL_STORAGE permission
- screen recorder can't record to /data/data/your.package/files directory because of permissions issue

**Comment by Nikitae57** [comment]
Linked to #407

**Comment by Nikitae57** [comment]
We discussed the idea to put all artifacts into Documents folder since it's a public folder and quick experiment showed us that we could use it without restrictions. With this approach we have to keep in mind that allure stores reports to /data/data. Ideally we want to save reports to the same place as other artifacts. We decided that we'll copy reports from /data/data to Documents and cover it with an optional flag in Kaspresso builder
