### ISSUE TITLE
VideoRecordingTestInterceptor not recording video

### ISSUE THREAD

**Issue by yeltayev22** [KasperskyLab/Kaspresso#421]
**Describe the bug**
VideoRecordingTestInterceptor not recording video in version 1.4.2(also there is a known bug with file directory creation which is fixed in 1.4.3) and 1.4.3. According to the logs, screenrecording starts and ends successfully, however, the file size is 0 MB. Checked on 1.4.1 everything works as expected.

**To Reproduce**
1. Run test with VideoRecordingTestInterceptor on kaspresso version 1.4.2
2. Check the screenrecord file

**Expected behavior**
1. Screenrecord file weighs much more than 0 MB.

**Screenshots**
https://freeimage.host/i/ypc5iJ

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android API 29

**Comment by Nikitae57** [comment]
Hi, @yeltayev22! Thank you for your submission! We're aware of this issue and already have a workaround which is implemented in the scope of the next release. 

If you're interested in the root cause of the problem - check out this [issue](https://issuetracker.google.com/issues/258277873). 
Updates on this topic would be posted [here](https://github.com/KasperskyLab/Kaspresso/issues/407) and [here](https://github.com/KasperskyLab/Kaspresso/issues/404)
