### ISSUE TITLE
Failure on DevicePermissionSampleTest.

### ISSUE THREAD

**Issue by victory316** [KasperskyLab/Kaspresso#495]
**Describe the bug**
permissionsSampleTest fails in DevicePermissionSampleTest on Google Pixel 4a.  Shell command must be modified for successful test. 

**To Reproduce**

- permissionsSampleTest fails in DevicePermissionSampleTest on Google Pixel 4a.

**Expected behavior**

- Example case should be passed.

**Screenshots**
<img width="1986" alt="스크린샷 2023-03-27 오후 2 44 03" src="https://user-images.githubusercontent.com/17717580/227851014-42259624-db76-4622-9439-c84f38a6f4e4.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a
 - OS: Android 
 - Version Android 13

**Additional context**

**Comment by Nikitae57** [comment]
Hi, @victory316! On the screenshot provided DevicePermissionsSampleTest fails on the 34th line. There's a call to the adbServer's method. In order to work it requires running the adbserver-desktop.jar before starting the test as it's described in the second point of the exception message. Please, try to do so and reopen the issues if this doesn't help
