### ISSUE TITLE
How to inject camera image with Kaspresso?

### ISSUE THREAD

**Issue by tofffee** [KasperskyLab/Kaspresso#587]
When opening the camera on the emulator, I need to dynamically substitute the qr code. I tried updating the virtual scene files, but the emulator needs to be restarted. How can I do that?

**Comment by Nikitae57** [comment]
Hi, @tofffee! Unfortunately, android API doesn't allow dynamic camera preview change. I would suggest you to implement a test camera instance that would use frames used to draw a preview surface from the prerecorded video or image rather than hardware camera. Check out [camera](https://developer.android.com/guide/topics/media/camera) adn [SurfaceView](https://developer.android.com/reference/android/view/SurfaceView) documentation

**Comment by tofffee** [comment]
Thank you

чт, 12 окт. 2023 г. в 15:49, Nikita ***@***.***>:
